# Generated by Django 3.2 on 2023-11-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesystem',
            name='cns_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gradesystem',
            name='iot_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gradesystem',
            name='ml_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gradesystem',
            name='spm_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gradesystem',
            name='web_marks',
            field=models.IntegerField(),
        ),
    ]
