# Generated by Django 3.2 on 2023-11-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20231124_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradesystem',
            old_name='cns_marks',
            new_name='CNS_marks',
        ),
        migrations.RenameField(
            model_name='gradesystem',
            old_name='iot_marks',
            new_name='IOT_marks',
        ),
        migrations.RenameField(
            model_name='gradesystem',
            old_name='ml_marks',
            new_name='ML_marks',
        ),
        migrations.RenameField(
            model_name='gradesystem',
            old_name='spm_marks',
            new_name='SPM_marks',
        ),
        migrations.RenameField(
            model_name='gradesystem',
            old_name='web_marks',
            new_name='WEB_marks',
        ),
    ]
