# Generated by Django 3.2 on 2023-11-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20231124_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesystem',
            name='s_name',
            field=models.CharField(default='no', max_length=250),
        ),
    ]
