# Generated by Django 3.2 on 2023-11-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_gradesystem_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesystem',
            name='total',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
