# Generated by Django 3.2 on 2023-12-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_remove_gradesystem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesystem',
            name='ML_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gradesystem',
            name='course',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gradesystem',
            name='s_name',
            field=models.CharField(max_length=250),
        ),
    ]
