# Generated by Django 3.2 on 2023-12-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=250)),
                ('studenthallticketno', models.IntegerField()),
                ('mlmarks', models.IntegerField()),
                ('iotmarks', models.IntegerField()),
                ('webmarks', models.IntegerField()),
                ('cnsmarks', models.IntegerField()),
                ('spmmarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='thomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
