# Generated by Django 3.2 on 2023-12-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studetails_thomepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='course',
            field=models.CharField(max_length=250),
        ),
    ]
