# Generated by Django 3.2 on 2023-12-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studetails',
            name='mlmarks',
            field=models.CharField(max_length=100),
        ),
    ]
