# Generated by Django 3.2 on 2023-12-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_studetails_mlmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studetails',
            name='mlmarks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
