# Generated by Django 3.2 on 2023-12-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_studetails_mlmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studetails',
            name='cnsmarks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studetails',
            name='iotmarks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studetails',
            name='spmmarks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studetails',
            name='webmarks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
